CREATE VIEW uvw_valet_car_wash
AS
(
SELECT PARKING_SLIP_ID, ENTRY_TIME, TIME(ENTRY_TIME), FLOOR_ID, VEHICLE_NUMBER FROM parking_slip
where TIME(ENTRY_TIME) > '08:00:00' AND TIME(ENTRY_TIME) < '16:00:00' AND FLOOR_ID = 1 AND IS_VALET =1 AND HAS_CAR_WASH = 1
)