CREATE TABLE floor (
    FLOOR_ID INT PRIMARY KEY AUTO_INCREMENT,
    PARKING_LOT_ID INT,
    FLOOR_NUMBER INT,
    MAX_HEIGHT_IN_INCHES INT,
    IS_COVERED VARCHAR(1),
    IS_ACCESSIBLE VARCHAR(1),
    IS_FLOOR_FULL VARCHAR(1),
    IS_RESERVED_REG_CUST INT
)