CREATE TABLE parking_slot (
    SLOT_ID int primary key AUTO_INCREMENT,
    PARKING_LOT_ID INT,
    FLOOR_ID INT,
    SLOT_NUMBER INT,
    WING_CODE VARCHAR(1),
    CONSTRAINT FK_PARKING_SLOT_PARKING_LOT_ID FOREIGN KEY(PARKING_LOT_ID) REFERENCES parking_lot(PARKING_LOT_ID),
    CONSTRAINT FK_PARKING_SLOT_FLOOR_ID FOREIGN KEY(FLOOR_ID) REFERENCES floor(FLOOR_ID)
)